name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/test.yml@${{ github.ref_name }}

  publish:
    uses: ewoks-kit/.github/.github/workflows/python-publish.yml@main
    needs: build
