name: Release

on:
  workflow_dispatch:

jobs:
  tests:
    uses: ewoks-kit/.github/.github/workflows/python-tests.yml@main

  checks:
    uses: ewoks-kit/.github/.github/workflows/python-check.yml@main

  docs:
    uses: ewoks-kit/.github/.github/workflows/python-docs.yml@main

  publish:
    uses: ewoks-kit/.github/.github/workflows/python-publish.yml@main
    needs:
      - tests
      - lint
      - docs
