name: Python Documentation

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version for documentation build"
        type: string
        default: "3.12"
      pre-build-commands:
        description: "Optional custom commands to run before building the documentation"
        type: string
        required: false
        default: ""

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: ewoks-kit/.github/.github/actions/setup-python-package@main
        with:
          python-version: ${{ inputs.python-version }}
          install-extras: "doc"

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run custom command
        if: ${{ inputs.pre-build-commands != '' }}
        run: ${{ inputs.pre-build-commands }}

      - name: Build documentation
        run: sphinx-build ./doc ./html
