name: Python Lint & Style & Security

on:
  workflow_call:
    inputs:
      enable-mypy:
        type: string
        default: "false"

jobs:
  checks:
    name: Python Lint & Style & Security
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: ruff
        run: |
          pip install ruff
          ruff --version
          ruff check .
          ruff format --check .

      - name: mypy
        if: inputs.enable-mypy == 'true'
        run: |
          pip install mypy
          mypy .
